app.setting: 'ad'

api:
  endpoint:
    manufacturer-url: 'http://${api.endpoint.base-uri}/api/v1/manufacturer'
    category-url: 'http://${api.endpoint.base-uri}/api/v1/category'
    product-url: 'http://${api.endpoint.base-uri}/api/v1/product'
    user-url: 'http://127.0.0.1:8081/api/v1/user'
    authentication-url: 'http://127.0.0.1:8081/api/v1/auth'
#    manufacturer-url: 'http://${api.endpoint.external-uri}/external/api/v1/manufacturer'
#    category-url: 'http://${api.endpoint.external-uri}/external/api/v1/category'
#    product-url: 'http://${api.endpoint.external-uri}/external/api/v1/product'
  connection:
    period: 100
    max-period: 10000 #Millis
    max-attempts: 3
    connect-timeout: 10000 #Millis
    #        connect-timeout-unit:
    read-timeout: 30000 #Millis
    #        read-timeout-unit:
    follow-redirects: true