spring.datasource:
  url: "jdbc:postgresql://localhost:5433/shop"
  username: '{cipher}AYBh7HZdtge12s29fOmVozPUEOXat/dErOyqww2SsJcMZ1R0QgEYX8mto50tVjrvAD5twlCun6wlEUC12dAYTOnZWgiTKfHz0HVuP6Bwuuv3QrnDzLSmtdyBXj+MVxiuyJ5lF/VRd0PGJ4ijvMOoEzcA+QDb15eqqogswO8gSCF/z4DGHikBr2KVufVF2drLZzBcE0bS8M3m4U4i8+A+r8uKbF4qleOkuOAWwGpVPhpq3gHCrp0yh3Lv5n06fCpl86tWhEGpJwPn1AJChQGoOAuQyfUDkBfTYms6Cs3Y+F9ZUd63f7f8Ljt1NsM+HJE0R6tnxF/F942iZeg4yWcC0UbdHhMna2v49a9WM7Gi611KOItr4ou2+3n+0CgrtSkaDT3Fxw8KRVWvJjauY9jhGg3A8EBE855AQxr4pslAkNSLJZut0gBmVp01M+1X8uzzVsRBfE/g9tcJEFsD2CbeSfBHQbxs16m/yua4bZ4swEkVjXoACjb0kC7lhx51YQNyPFFxbRyej8QoH+yJK2kbBym/9AZqwG3e9UqthER7rPHXtg=='
  password: '{cipher}AYC5w2JCZuLXbLiUnPQ8W1Dw6GnGNCGV/F+PbaAWBrT5+AHGDOhleshy8+/gRwfPDIGIZKsXL9SscSDnI4lLgfG73Ep6CE446feKjD+nT7xFBQRiRbjQybzt7Nw5xO3xZbDLdFg2kJAbrdVJrB/qSWCk6mpb2+TgIcVaHOOBbOzpU9zCJ5NWG7fpoTZwa8OpAu+1DZ57pag3YVO25OaSm3UnxT6t6IcIjXqrnwTSVIM30k1a20DKYVGUHFWOyOL5NFM98/rPUJZ19z8o4VHDoOB933ccQZyEuUOUNAVc2LatqWjeuJRQjBmEBEBxYbVgUfnbX9ZYUXOEBnSCvfPYgdSCiziV1RWmCaLUc1/B5+Fp7nl/IjThwieNJI2TOtCFhSB5aAAar6DDozj44YMIPA5zan5Ns/zYoCjbsWnMMbH9uNV8Xe/6q9H6UFWnb20bJp58v5UQvDlW3rT3QVXpBAUyEzzgT6At65W1jlGXUnvZR9KRhnv0CxIsmNdhdx9lefo283GKkDRAY5FsMGuUQ0UrLgnSpwIDqxXzbqSompU0/A=='

#  username: "postgres"
#  password: "minx"

api:
  endpoint:
    base-uri: '127.0.0.1:8080'
#    base-uri: '127.0.0.1:8081'
app.setting: 'dv'